### ISSUE TITLE
MockGen Crashing With EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by commonsguy** [doppllib/core-doppl#12]
I am attempting to get `@MockGen` working, but attempts to call methods on a spy are crashing on iOS.

[DopplTests-20171030.zip](https://github.com/doppllib/core-doppl/files/1427564/DopplTests-20171030.zip)
 
After a fair bit of experimentation, I'm now down to this:

```java
@MockGen(classes="com.commonsware.myapplication.ExampleUnitTest.RunnableWrapper")
public class ExampleUnitTest {
  @Test
  public void addition_isCorrect() throws Exception {
    assertEquals(4, 2+2);
  }

  @Test
  public void addition_isStillCorrect() {
    assertEquals(4, 2+2);
  }

  @Test
  public void timer() throws InterruptedException {
//    ScheduledExecutorService scheduler=Executors.newSingleThreadScheduledExecutor();
    Runnable thingy=spy(new RunnableWrapper(new Runnable() {
      @Override
      public void run() {
        // TODO
      }
    }));

    verify(thingy, never()).run();

    thingy.run();

//    scheduler.schedule(thingy, 200, TimeUnit.MILLISECONDS);
/*    scheduler.schedule(new Runnable() {
      @Override
      public void run() {

      }
    }, 200, TimeUnit.MILLISECONDS);
*/
//    Thread.sleep(500);
//    verify(thingy, times(1)).run();
  }

  public static class RunnableWrapper implements Runnable {
    final Runnable wrapped;

    protected RunnableWrapper(Runnable wrapped) {
      this.wrapped = wrapped;
    }

    @Override
    public void run() {
      wrapped.run();
    }
  }
}
```

I create a spy, and when I call `run()` on the spy, I get `EXC_BAD_ACCESS`:

<img width="830" alt="screen shot 2017-10-30 at 10 44 33" src="https://user-images.githubusercontent.com/103772/32176949-60b59684-bd5f-11e7-85e1-7e7630366328.png">

Notable differences from the `retrofit` Doppl tests:

- I am using `testAnnotationProcessor`, as I cannot get the `net.ltgt` stuff to give me a `testApt` option

- I am using `co.doppl.lib:testapt:0.8.5`, as `0.8.1` does not seem to exist in the Maven repo

**Comment by kpgalligan** [comment]
The generated code also needs to be seen as something to be translated by the plugin. Mockgen will make a class whose name ends with $Moxy. The translatePattern in the zip above does not match the generated code.

At runtime, Mockito will look for the special class name using reflection, and if not found, will just create a mock. For spy, doing that will fail.

To be 100% clear, "MockGen" is a hack until mockito is fully functional with J2objc/Doppl

![screen shot 2017-10-30 at 11 19 43 am](https://user-images.githubusercontent.com/68384/32178932-6d068e0c-bd64-11e7-8fa8-1204b2f1f4c4.png)

![mockout](https://user-images.githubusercontent.com/68384/32178938-70da1788-bd64-11e7-90dd-30e8a453eb67.png)

**Comment by commonsguy** [comment]
Note to self: changing `dopplConfig` sometimes requires a clean-and-rebuild in Android Studio.

But, yes, I can confirm that this clears up the problem. Thanks!
